version: "3.7"
services:
  config:
    image: bookstore-config
    ports:
      - "8888:8888"
    environment:
      CONFIG_PASSWORD: ${CONFIG_PASSWORD}
      ENCRYPT_PASSWORD: ${ENCRYPT_PASSWORD}

  registry:
    image: bookstore-registry
    ports:
      - "8761:8761"
    depends_on:
      - config
    restart: on-failure
    environment:
      CONFIG_PASSWORD: ${CONFIG_PASSWORD}

  authdb:
    image: mariadb
    ports:
      - "4000:3306"
    volumes:
      - authdb_data:/var/lib/mysql
      - ./deploy/config/authdb.sql:/docker-entrypoint-initdb.d/authdb.sql
    environment:
      MYSQL_DATABASE: ${AUTHDB_DB}
      MYSQL_ROOT_PASSWORD: ${AUTHDB_ROOT}
      MYSQL_USER: ${AUTHDB_USER}
      MYSQL_PASSWORD: ${AUTHDB_PASSWORD}

  authserv:
    image: bookstore-authserv
    ports:
      - "8081:8080"
    depends_on:
      - config
      - authdb
      - registry
    restart: on-failure
    environment:
      CONFIG_PASSWORD: ${CONFIG_PASSWORD}
      DB_USER: ${AUTHDB_USER}
      DB_PASSWORD: ${AUTHDB_PASSWORD}

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq_directory:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}

  bookdb:
    image: mongo
    ports:
      - "4001:27017"
    volumes:
      - bookdb_data:/data/db
      - bookdb_config:/data/configdb

  bookserv:
    image: bookstore-bookserv
    ports:
      - "8082:8080"
      - "9082:8081"
    depends_on:
      - config
      - bookdb
      - authserv
      - registry
    restart: on-failure
    environment:
      CONFIG_PASSWORD: ${CONFIG_PASSWORD}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASS}

  logserv:
    image: bookstore-logserv
    depends_on:
      - rabbitmq
    restart: on-failure
    environment:
      CONFIG_PASSWORD: ${CONFIG_PASSWORD}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASS}

  gateway:
    image: bookstore-gateway
    ports:
      - "8083:8080"
    restart: on-failure
    environment:
      CONFIG_PASSWORD: ${CONFIG_PASSWORD}

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./deploy/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_USER_PASS}

volumes:
  authdb_data:
  bookdb_data:
  bookdb_config:
  grafana:
  prometheus:
  rabbitmq_directory: