version: "3.7"
services:
  config:
    image: bookstore-config
    ports:
      - "8888:8888"
    environment:
      CONFIG_PASSWORD: ${CONFIG_PASSWORD}
      ENCRYPT_PASSWORD: ${ENCRYPT_PASSWORD}

  registry:
    image: bookstore-registry
    ports:
      - "8761:8761"
    depends_on:
      - config
    restart: on-failure
    environment:
      CONFIG_PASSWORD: ${CONFIG_PASSWORD}

  authdb:
    image: mariadb
    ports:
      - "4000:3306"
    volumes:
      - bookstore-authdb:/var/lib/mysql
      - .\config\authdb.sql:/docker-entrypoint-initdb.d/authdb.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${AUTHDB_ROOT_PASS}
      MYSQL_DATABASE: ${AUTHDB_DB}
      MYSQL_USER: ${AUTHDB_USER}
      MYSQL_PASSWORD: ${AUTHDB_PASSWORD}

  authserv:
    image: bookstore-authserv
    ports:
      - "8081:8080"
    depends_on:
      - config
      - authdb
      - registry
    restart: on-failure
    environment:
      CONFIG_PASSWORD: ${CONFIG_PASSWORD}
      AUTHDB_DB: ${AUTHDB_DB}
      AUTHDB_USER: ${AUTHDB_USER}
      AUTHDB_PASSWORD: ${AUTHDB_PASSWORD}

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    volumes:
      - rabbit:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}

  bookdb:
    image: mongo
    ports:
      - "4001:27017"
    volumes:
      - bookstore-bookdb:/data/db

  bookserv:
    image: bookstore-bookserv
    ports:
      - "8082:8080"
      - "9082:8081"
    depends_on:
      - config
      - bookdb
      - authserv
      - registry
    restart: on-failure
    environment:
      CONFIG_PASSWORD: ${CONFIG_PASSWORD}
      BOOKDB_DB: ${BOOKDB_DB}
      BOOKSERV_PASSWORD: ${BOOKSERV_PASSWORD}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASS}
      ACTUATOR_PASSWORD: ${ACTUATOR_PASSWORD}

  logserv:
    image: bookstore-logserv
    depends_on:
      - rabbitmq
    restart: on-failure
    environment:
      CONFIG_PASSWORD: ${CONFIG_PASSWORD}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASS}

  gateway:
    image: bookstore-gateway
    ports:
      - "8083:8080"
    restart: on-failure
    environment:
      CONFIG_PASSWORD: ${CONFIG_PASSWORD}

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - .\config\prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_USER_PASS}

volumes:
  bookstore-authdb:
  bookstore-bookdb:
  grafana:
  prometheus:
  rabbit: