eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
      
logging:
  level:
    org.springframework.security: INFO
    
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:4444/uaa/users/current