eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka

logging:
  level:
    org.springframework.security: INFO

security:
  oauth2:
    resource:
      user-info-uri: http://authserv:8081/uaa/users/current

spring:
  rabbitmq:
    host: rabbitmq
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}
    listener:
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true