server:
  servlet:
    context-path: /auth

spring:
  datasource:
    url: jdbc:mysql://authdb:3306/authdb?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect