server:
  servlet:
    context-path: /auth

spring:
  datasource:
    url: jdbc:mysql://authdb:3306/${AUTHDB_DB}?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect