server:
  servlet:
    context-path: /auth

spring:
  data:
    mongodb:
      host: authdb
      username: ${AUTHDB_USER}
      password: ${AUTHDB_PASSWORD}
      database: ${AUTHDB_DB}
      port: 27017