server:
  servlet:
    context-path: /books

spring:
  data:
    mongodb:
      host: bookdb
      database: ${BOOKDB_DB}
      port: 27017
  cloud:
    stream:
      bindings:
        bookRegistrationChannel:
          destination: registrationChannel
      default:
        contentType: application/json
  security:
    user:
      password: ${ACTUATOR_PASSWORD}

security:
  oauth2:
    client:
      clientId: book
      clientSecret: ${BOOKSERV_PASSWORD}
      accessTokenUri: http://authserv:8080/auth/oauth/token
      grant-type: client_credentials
      scope: server

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: info, health, prometheus