server:
  port: 2222
  
spring:
  data:
    mongodb:
      host: localhost
      database: bookstore
      port: 27017
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka