server:
  port: 2222
  servlet:
    context-path: /books
  
spring:
  data:
    mongodb:
      host: localhost
      database: bookstore
      port: 27017
  cloud:
    stream:
      bindings:
        bookRegistrationChannel:
          destination: logExchange
      default:
        contentType: application/json
      rabbit:
        bindings:
          bookRegistrationChannel:
            producer:
              routing-key-expression: "'book.created'"
      
security:
  oauth2:
    client:
      clientId: book-serv
      clientSecret: 123456
      accessTokenUri: http://localhost:4444/uaa/oauth/token
      grant-type: client_credentials
      scope: server