server:
  servlet:
    context-path: /books

spring:
  data:
    mongodb:
      host: bookdb
      username: ${AUTHDB_USER}
      password: ${AUTHDB_PASSWORD}
      database: ${AUTHDB_DB}
      port: 27017
  cloud:
    stream:
      bindings:
        bookRegistrationChannel:
          destination: registrationChannel
      default:
        contentType: application/json

security:
  oauth2:
    client:
      clientId: book-serv
      clientSecret: ${BOOKSERV-PASSWORD}
      accessTokenUri: http://authserv:8081/uaa/oauth/token
      grant-type: client_credentials
      scope: server