spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bookserv
          uri: lb://book-serv
          predicates:
            - Path=/libros/**
          filters:
            - RewritePath=/libros/(?<segment>.*), /books/$\{segment}