server:
  port: 3333
  
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: logExchange
          group: log-queue
      rabbit:
        bindings:
          input:
            consumer:
              bindingRoutingKey: "*.created"
              exchangeType: topic

security:
  oauth2:
    client:
      clientId: log-serv
      clientSecret: ${LOGSERV-PASSWORD}
      accessTokenUri: http://localhost:4444/uaa/oauth/token
      grant-type: client_credentials
      scope: server