server:
  port: 3333
  
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: logExchange
          group: log-queue

security:
  oauth2:
    client:
      clientId: log-serv
      clientSecret: 123456
      accessTokenUri: http://localhost:4444/uaa/oauth/token
      grant-type: client_credentials
      scope: server