server:
  port: 3333
  
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: registrationChannel
          group: log-queue
      rabbit:
        bindings:
          input:
            consumer:
              bindingRoutingKey: "*.created"
              exchangeType: topic