spring:
  application:
    name: gateway-serv
  cloud:
    config:
      uri: http://localhost:8888

zuul:
  ignoredServices: '*'
  routes:
    book-serv:
      path: /books/**
      serviceId: book-serv
      stripPrefix: false
      sensitiveHeaders:
      