spring:
  application:
    name: gateway-serv
  cloud:
    config:
      uri: http://localhost:8888
    gateway:
      routes:
      - id: bookserv
        uri: http://localhost:2222
        predicates:
        - Path=/libros/**
        filters:
        - RewritePath=/libros/(?<segment>.*), /books/$\{segment}
