spring:
  application:
    name: book-serv
  cloud:
    config:
      uri: http://localhost:8888
    stream:
      bindings:
        bookRegistrationChannel:
          destination: registrationChannel
      default:
        contentType: application/json