server:
  port: 8888

spring:
  security:
    user:
      password: ${CONFIG_PASSWORD}
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
  profiles:
    active: native